[package]
name = "Emit"
version = "0.1.0"
authors = ["marek counts <marek.counts@outlook.com>"]

[lib]
name = "emit_lib"
path = "src/lib.rs"

[[bin]]
name = "emit"
path = "src/bin/main.rs"

[dependencies]
clap = "~2.32"
hyper = "0.11.22"
http = "0.1.7"
futures = "0.1.21"
reqwest = "0.8.8"